---
abstract: 'Template plugin for parsing HTTP User-Agent string'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-HTTP-UserAgent
no_index:
  directory:
    - t
    - inc
requires:
  HTML::ParseBrowser: 1.05
  Template::Plugin: 0
  Template::Test: 0
resources:
  repository: https://github.com/neilbowers/Template-Plugin-HTTP-UserAgent
version: 0.01
